In [1]:
import numpy
import pandas

In [2]:
data = pandas.read_csv('fetal_health.csv')
df = pandas.DataFrame(data)
df

,baseline value,accelerations,fetal_movement,uterine_contractions,light_decelerations,severe_decelerations,prolongued_decelerations,abnormal_short_term_variability,mean_value_of_short_term_variability,percentage_of_time_with_abnormal_long_term_variability,...,histogram_min,histogram_max,histogram_number_of_peaks,histogram_number_of_zeroes,histogram_mode,histogram_mean,histogram_median,histogram_variance,histogram_tendency,fetal_health
0,120.0,0.000,0.000,0.000,0.000,0.0,0.0,73.0,0.5,43.0,...,62.0,126.0,2.0,0.0,120.0,137.0,121.0,73.0,1.0,2.0
1,132.0,0.006,0.000,0.006,0.003,0.0,0.0,17.0,2.1,0.0,...,68.0,198.0,6.0,1.0,141.0,136.0,140.0,12.0,0.0,1.0
2,133.0,0.003,0.000,0.008,0.003,0.0,0.0,16.0,2.1,0.0,...,68.0,198.0,5.0,1.0,141.0,135.0,138.0,13.0,0.0,1.0
3,134.0,0.003,0.000,0.008,0.003,0.0,0.0,16.0,2.4,0.0,...,53.0,170.0,11.0,0.0,137.0,134.0,137.0,13.0,1.0,1.0
4,132.0,0.007,0.000,0.008,0.000,0.0,0.0,16.0,2.4,0.0,...,53.0,170.0,9.0,0.0,137.0,136.0,138.0,11.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2121,140.0,0.000,0.000,0.007,0.000,0.0,0.0,79.0,0.2,25.0,...,137.0,177.0,4.0,0.0,153.0,150.0,152.0,2.0,0.0,2.0
2122,140.0,0.001,0.000,0.007,0.000,0.0,0.0,78.0,0.4,22.0,...,103.0,169.0,6.0,0.0,152.0,148.0,151.0,3.0,1.0,2.0
2123,140.0,0.001,0.000,0.007,0.000,0.0,0.0,79.0,0.4,20.0,...,103.0,170.0,5.0,0.0,153.0,148.0,152.0,4.0,1.0,2.0
2124,140.0,0.001,0.000,0.006,0.000,0.0,0.0,78.0,0.4,27.0,...,103.0,169.0,6.0,0.0,152.0,147.0,151.0,4.0,1.0,2.0
2125,142.0,0.002,0.002,0.008,0.000,0.0,0.0,74.0,0.4,36.0,...,117.0,159.0,2.0,1.0,145.0,143.0,145.0,1.0,0.0,1.0

In [3]:
df.isna().sum()

baseline value                                            0
accelerations                                             0
fetal_movement                                            0
uterine_contractions                                      0
light_decelerations                                       0
severe_decelerations                                      0
prolongued_decelerations                                  0
abnormal_short_term_variability                           0
mean_value_of_short_term_variability                      0
percentage_of_time_with_abnormal_long_term_variability    0
mean_value_of_long_term_variability                       0
histogram_width                                           0
histogram_min                                             0
histogram_max                                             0
histogram_number_of_peaks                                 0
histogram_number_of_zeroes                                0
histogram_mode                                            0
histogram_mean                                            0
histogram_median                                          0
histogram_variance                                        0
histogram_tendency                                        0
fetal_health                                              0
dtype: int64

In [4]:
df.dtypes

baseline value                                            float64
accelerations                                             float64
fetal_movement                                            float64
uterine_contractions                                      float64
light_decelerations                                       float64
severe_decelerations                                      float64
prolongued_decelerations                                  float64
abnormal_short_term_variability                           float64
mean_value_of_short_term_variability                      float64
percentage_of_time_with_abnormal_long_term_variability    float64
mean_value_of_long_term_variability                       float64
histogram_width                                           float64
histogram_min                                             float64
histogram_max                                             float64
histogram_number_of_peaks                                 float64
histogram_number_of_zeroes                                float64
histogram_mode                                            float64
histogram_mean                                            float64
histogram_median                                          float64
histogram_variance                                        float64
histogram_tendency                                        float64
fetal_health                                              float64
dtype: object

In [5]:
X = df.iloc[:,:-1]
X
Y = df.iloc[:,-1]
Y

0       2.0
1       1.0
2       1.0
3       1.0
4       1.0
       ...
2121    2.0
2122    2.0
2123    2.0
2124    2.0
2125    1.0
Name: fetal_health, Length: 2126, dtype: float64

In [6]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3)

X_train

,baseline value,accelerations,fetal_movement,uterine_contractions,light_decelerations,severe_decelerations,prolongued_decelerations,abnormal_short_term_variability,mean_value_of_short_term_variability,percentage_of_time_with_abnormal_long_term_variability,...,histogram_width,histogram_min,histogram_max,histogram_number_of_peaks,histogram_number_of_zeroes,histogram_mode,histogram_mean,histogram_median,histogram_variance,histogram_tendency
1408,145.0,0.005,0.000,0.004,0.000,0.0,0.000,51.0,0.7,5.0,...,67.0,104.0,171.0,5.0,0.0,149.0,153.0,154.0,5.0,1.0
1349,128.0,0.000,0.028,0.004,0.004,0.0,0.004,36.0,2.6,0.0,...,120.0,54.0,174.0,8.0,2.0,75.0,91.0,79.0,108.0,-1.0
107,125.0,0.007,0.004,0.006,0.002,0.0,0.000,22.0,2.1,0.0,...,105.0,73.0,178.0,8.0,0.0,126.0,126.0,128.0,11.0,0.0
1755,134.0,0.003,0.000,0.000,0.000,0.0,0.005,65.0,1.8,0.0,...,114.0,66.0,180.0,8.0,1.0,88.0,100.0,101.0,83.0,-1.0
1906,130.0,0.001,0.001,0.012,0.010,0.0,0.001,62.0,2.2,0.0,...,161.0,50.0,211.0,9.0,0.0,60.0,89.0,113.0,250.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1866,138.0,0.015,0.000,0.003,0.000,0.0,0.000,50.0,1.0,0.0,...,72.0,99.0,171.0,5.0,1.0,147.0,147.0,148.0,7.0,1.0
2099,133.0,0.000,0.009,0.005,0.000,0.0,0.000,72.0,2.1,11.0,...,60.0,91.0,151.0,10.0,0.0,136.0,132.0,136.0,1.0,1.0
217,127.0,0.000,0.005,0.000,0.000,0.0,0.000,61.0,0.6,4.0,...,89.0,62.0,151.0,4.0,0.0,131.0,129.0,131.0,2.0,1.0
1332,128.0,0.008,0.010,0.003,0.005,0.0,0.000,27.0,1.9,0.0,...,141.0,57.0,198.0,12.0,0.0,135.0,125.0,135.0,59.0,0.0
1776,120.0,0.000,0.000,0.005,0.009,0.0,0.002,64.0,1.7,0.0,...,111.0,63.0,174.0,10.0,1.0,86.0,93.0,101.0,42.0,-1.0

In [7]:
df.isna().sum()

baseline value                                            0
accelerations                                             0
fetal_movement                                            0
uterine_contractions                                      0
light_decelerations                                       0
severe_decelerations                                      0
prolongued_decelerations                                  0
abnormal_short_term_variability                           0
mean_value_of_short_term_variability                      0
percentage_of_time_with_abnormal_long_term_variability    0
mean_value_of_long_term_variability                       0
histogram_width                                           0
histogram_min                                             0
histogram_max                                             0
histogram_number_of_peaks                                 0
histogram_number_of_zeroes                                0
histogram_mode                                            0
histogram_mean                                            0
histogram_median                                          0
histogram_variance                                        0
histogram_tendency                                        0
fetal_health                                              0
dtype: int64

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [9]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()

model = knn.fit(X_train,Y_train)

Y_pred = model.predict(X_test)

In [10]:
from sklearn.metrics import accuracy_score

print(accuracy_score(Y_test,Y_pred))

0.8887147335423198

In [11]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test,Y_pred)
cm

array([[465,  14,   2],
       [ 35,  61,   2],
       [  7,  11,  41]])