In [1]:
import numpy
import pandas

In [2]:
data = pandas.read_csv("diabetes.csv")
df = pandas.DataFrame(data)
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [3]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [4]:
# target >>> outcome
# input features >>> Pregnancies	Glucose	BloodPressure	SkinThickness	Insulin	BMI	DiabetesPedigreeFunction	Age

# No missing values so no need of filling

# scikit-learn >>> Contains tools to build, train, test and evaluating ML models easily
# ==========================================================================================================

In [5]:
# Splitting
#=========================
X = df.iloc[:,:-1]

Y = df.iloc[:,-1]
Y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

Input Features >>> 70 % training  30 % testing >>> X_train  X_test
Target >>>         70 % training  30 % evaluation >>> Y_train  Y_test

In [6]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3)

X_train

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
415,3,173,84,33,474,35.7,0.258,22
553,1,88,62,24,44,29.9,0.422,23
758,1,106,76,0,0,37.5,0.197,26
73,4,129,86,20,270,35.1,0.231,23
480,3,158,70,30,328,35.5,0.344,35
...,...,...,...,...,...,...,...,...
638,7,97,76,32,91,40.9,0.871,32
605,1,124,60,32,0,35.8,0.514,21
659,3,80,82,31,70,34.2,1.292,27
223,7,142,60,33,190,28.8,0.687,61
65,5,99,74,27,0,29.0,0.203,32

In [7]:
# Z = (x - mean) / standardDeviation    >>>   Standard Scaler

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_train

"""
No need to give X_test to fit method
"""
X_test = scaler.transform(X_test)
X_test

array([[-0.84813454, -1.27785067,  0.27071413, ...,  1.85219179,
         1.97481059, -0.09589451],
       [-1.1483641 , -0.63219221, -0.18028945, ..., -0.985154  ,
        -0.71551387, -0.93869894],
       [ 0.65301328, -1.31013359,  0.57138317, ...,  1.00229559,
        -0.90342943, -0.43301628],
       ...,
       [ 0.95324284,  0.85282224,  0.37093714, ...,  0.94999428,
        -0.65287535,  0.83119037],
       [-0.84813454, -0.01881668,  0.57138317, ...,  0.88461765,
         2.18151771,  0.66262948],
       [ 0.65301328,  0.14259794,  0.37093714, ...,  0.21777601,
        -1.07881729,  1.75827525]], shape=(231, 8))

In [8]:
"""
KNN algorithm 
"""
# Training
from sklearn.neighbors import KNeighborsClassifier  # class method KNN
knn = KNeighborsClassifier()
knn = knn.fit(X_train,Y_train)

In [9]:
# Testing
y_pred = knn.predict(X_test)    # Model will predict the result for untrained data
y_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0])

PERFORMANCE EVALUATION

In [10]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_pred,Y_test))

0.7316017316017316

In [11]:
# Acccuracy Score = correct predictions / total no. of predictions
# Recall
# Precision
# f1-score
# Confusion matrix (Only for classification)

In [12]:
# Confusion matrix
# TruePositive, TrueNegative, FalsePositive, FalseNegative

# real result      model result
#     1                 1       #True Positive
#     1                 0       #False Negative
#     0                 1       #False Positive
#     0                 0       #True Negative

In [13]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test,y_pred)
cm

array([[127,  25],
       [ 37,  42]])