In [132]:
import numpy
import pandas
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to C:\Users\Anand
[nltk_data]     Vinodkumar\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to C:\Users\Anand
[nltk_data]     Vinodkumar\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\Anand
[nltk_data]     Vinodkumar\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\Anand
[nltk_data]     Vinodkumar\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [133]:
data = pandas.read_csv('twitter_validation.csv',header=None)
df = pandas.DataFrame(data)
df

,0,1,2,3
0,3364,Facebook,Irrelevant,I mentioned on Facebook that I was struggling ...
1,352,Amazon,Neutral,BBC News - Amazon boss Jeff Bezos rejects clai...
2,8312,Microsoft,Negative,@Microsoft Why do I pay for WORD when it funct...
3,4371,CS-GO,Negative,"CSGO matchmaking is so full of closet hacking,..."
4,4433,Google,Neutral,Now the President is slapping Americans in the...
...,...,...,...,...
995,4891,GrandTheftAuto(GTA),Irrelevant,⭐️ Toronto is the arts and culture capital of ...
996,4359,CS-GO,Irrelevant,tHIS IS ACTUALLY A GOOD MOVE TOT BRING MORE VI...
997,2652,Borderlands,Positive,Today sucked so it’s time to drink wine n play...
998,8069,Microsoft,Positive,Bought a fraction of Microsoft today. Small wins.
999,6960,johnson&johnson,Neutral,Johnson & Johnson to stop selling talc baby po...

In [134]:
# Add column names
df.columns = ['ID','Entity','Nature of comment','Comment']
df

,ID,Entity,Nature of comment,Comment
0,3364,Facebook,Irrelevant,I mentioned on Facebook that I was struggling ...
1,352,Amazon,Neutral,BBC News - Amazon boss Jeff Bezos rejects clai...
2,8312,Microsoft,Negative,@Microsoft Why do I pay for WORD when it funct...
3,4371,CS-GO,Negative,"CSGO matchmaking is so full of closet hacking,..."
4,4433,Google,Neutral,Now the President is slapping Americans in the...
...,...,...,...,...
995,4891,GrandTheftAuto(GTA),Irrelevant,⭐️ Toronto is the arts and culture capital of ...
996,4359,CS-GO,Irrelevant,tHIS IS ACTUALLY A GOOD MOVE TOT BRING MORE VI...
997,2652,Borderlands,Positive,Today sucked so it’s time to drink wine n play...
998,8069,Microsoft,Positive,Bought a fraction of Microsoft today. Small wins.
999,6960,johnson&johnson,Neutral,Johnson & Johnson to stop selling talc baby po...

In [135]:
# Convert to lowercase
df['Comment'] = df['Comment'].str.lower()
df

,ID,Entity,Nature of comment,Comment
0,3364,Facebook,Irrelevant,i mentioned on facebook that i was struggling ...
1,352,Amazon,Neutral,bbc news - amazon boss jeff bezos rejects clai...
2,8312,Microsoft,Negative,@microsoft why do i pay for word when it funct...
3,4371,CS-GO,Negative,"csgo matchmaking is so full of closet hacking,..."
4,4433,Google,Neutral,now the president is slapping americans in the...
...,...,...,...,...
995,4891,GrandTheftAuto(GTA),Irrelevant,⭐️ toronto is the arts and culture capital of ...
996,4359,CS-GO,Irrelevant,this is actually a good move tot bring more vi...
997,2652,Borderlands,Positive,today sucked so it’s time to drink wine n play...
998,8069,Microsoft,Positive,bought a fraction of microsoft today. small wins.
999,6960,johnson&johnson,Neutral,johnson & johnson to stop selling talc baby po...

In [136]:
import re

text = "python is a language https://www.google.com/"

text = re.sub(r'https\S+',"",text)

text

'python is a language '

In [137]:
# Remove urls and special characters

def replace_url(text):

    text = re.sub(r'http\S+',"",text)

    text = re.sub(r'[^a-z\s]',"",text)

    return text

df['Comment'] = df['Comment'].apply(replace_url)

df['Comment']

0      i mentioned on facebook that i was struggling ...
1      bbc news  amazon boss jeff bezos rejects claim...
2      microsoft why do i pay for word when it functi...
3      csgo matchmaking is so full of closet hacking ...
4      now the president is slapping americans in the...
                             ...
995     toronto is the arts and culture capital of ca...
996    this is actually a good move tot bring more vi...
997    today sucked so its time to drink wine n play ...
998      bought a fraction of microsoft today small wins
999    johnson  johnson to stop selling talc baby pow...
Name: Comment, Length: 1000, dtype: object

In [138]:
# Tokenisation

from nltk.tokenize import word_tokenize

df['Tokens'] = df['Comment'].apply(word_tokenize)

df['Tokens']

0      [i, mentioned, on, facebook, that, i, was, str...
1      [bbc, news, amazon, boss, jeff, bezos, rejects...
2      [microsoft, why, do, i, pay, for, word, when, ...
3      [csgo, matchmaking, is, so, full, of, closet, ...
4      [now, the, president, is, slapping, americans,...
                             ...
995    [toronto, is, the, arts, and, culture, capital...
996    [this, is, actually, a, good, move, tot, bring...
997    [today, sucked, so, its, time, to, drink, wine...
998    [bought, a, fraction, of, microsoft, today, sm...
999    [johnson, johnson, to, stop, selling, talc, ba...
Name: Tokens, Length: 1000, dtype: object

In [139]:
# Removing stopwords

from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

df['Tokens'] = df['Tokens'].apply(lambda a:[i for i in a if i not in stop_words])

df['Tokens']

0      [mentioned, facebook, struggling, motivation, ...
1      [bbc, news, amazon, boss, jeff, bezos, rejects...
2      [microsoft, pay, word, functions, poorly, sams...
3      [csgo, matchmaking, full, closet, hacking, tru...
4      [president, slapping, americans, face, really,...
                             ...
995    [toronto, arts, culture, capital, canada, wond...
996    [actually, good, move, tot, bring, viewers, on...
997    [today, sucked, time, drink, wine, n, play, bo...
998    [bought, fraction, microsoft, today, small, wins]
999    [johnson, johnson, stop, selling, talc, baby, ...
Name: Tokens, Length: 1000, dtype: object

In [140]:
# Lemmitzation

from nltk.stem import PorterStemmer

stemmer = PorterStemmer() # Used for stemming each token in each row

df['Tokens'] = df['Tokens'].apply(lambda a:[stemmer.stem(i) for i in a])

df['Tokens']

0      [mention, facebook, struggl, motiv, go, run, d...
1      [bbc, news, amazon, boss, jeff, bezo, reject, ...
2      [microsoft, pay, word, function, poorli, samsu...
3      [csgo, matchmak, full, closet, hack, truli, aw...
4      [presid, slap, american, face, realli, commit,...
                             ...
995    [toronto, art, cultur, capit, canada, wonder, ...
996    [actual, good, move, tot, bring, viewer, one, ...
997    [today, suck, time, drink, wine, n, play, bord...
998     [bought, fraction, microsoft, today, small, win]
999    [johnson, johnson, stop, sell, talc, babi, pow...
Name: Tokens, Length: 1000, dtype: object

In [141]:
# Convert back to text
# [mention, facebook, struggl, motiv, go, run, d...] -> "mention facebook struggl motiv go run d..."
df['Text'] = df['Tokens'].apply(lambda a: " ".join(a))
df['Text']

0      mention facebook struggl motiv go run day tran...
1      bbc news amazon boss jeff bezo reject claim co...
2      microsoft pay word function poorli samsungu ch...
3           csgo matchmak full closet hack truli aw game
4      presid slap american face realli commit unlaw ...
                             ...
995    toronto art cultur capit canada wonder want st...
996    actual good move tot bring viewer one peopl go...
997    today suck time drink wine n play borderland s...
998            bought fraction microsoft today small win
999    johnson johnson stop sell talc babi powder us ...
Name: Text, Length: 1000, dtype: object

In [142]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfid = TfidfVectorizer()

X = tfid.fit_transform(df['Text'])

X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 11838 stored elements and shape (1000, 4229)>

In [143]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

Y = le.fit_transform(df['Nature of comment'])

Y

array([0, 2, 1, 1, 2, 1, 3, 3, 3, 1, 3, 3, 1, 2, 1, 3, 3, 1, 3, 1, 1, 2,
       0, 1, 2, 2, 1, 0, 0, 1, 3, 3, 1, 3, 1, 2, 2, 0, 3, 2, 3, 2, 2, 2,
       3, 2, 1, 1, 1, 2, 3, 1, 1, 3, 3, 3, 3, 3, 1, 0, 1, 3, 3, 0, 1, 2,
       1, 0, 2, 1, 3, 1, 1, 3, 3, 0, 3, 0, 2, 2, 2, 3, 3, 2, 3, 2, 1, 0,
       1, 2, 2, 1, 3, 0, 0, 1, 1, 1, 2, 3, 2, 1, 3, 3, 2, 3, 2, 3, 1, 2,
       2, 2, 1, 2, 1, 2, 2, 3, 3, 2, 1, 1, 3, 1, 2, 1, 3, 2, 1, 2, 0, 3,
       2, 3, 3, 0, 2, 2, 0, 0, 0, 2, 2, 0, 0, 0, 3, 2, 3, 0, 3, 1, 2, 2,
       2, 0, 2, 1, 2, 3, 1, 2, 1, 0, 0, 0, 2, 1, 1, 1, 3, 3, 3, 2, 2, 3,
       0, 2, 2, 2, 3, 2, 1, 1, 2, 3, 3, 0, 0, 2, 3, 3, 2, 0, 2, 1, 1, 1,
       1, 3, 2, 2, 3, 3, 3, 3, 1, 3, 3, 0, 2, 0, 1, 1, 0, 0, 1, 3, 3, 1,
       0, 1, 3, 3, 1, 0, 0, 3, 3, 1, 3, 0, 2, 0, 0, 1, 2, 2, 3, 1, 0, 0,
       3, 3, 0, 0, 2, 3, 1, 1, 3, 3, 3, 3, 2, 2, 3, 1, 2, 3, 2, 1, 2, 2,
       1, 3, 3, 0, 1, 2, 0, 3, 2, 0, 1, 2, 1, 3, 3, 1, 1, 1, 3, 1, 2, 3,
       2, 2, 1, 3, 1, 3, 1, 0, 2, 2, 3, 1, 2, 1, 0, 3, 1, 3, 0, 3, 3, 3,
       3, 3, 1, 1, 3, 1, 2, 2, 2, 3, 0, 2, 3, 0, 1, 2, 2, 0, 2, 2, 0, 1,
       3, 1, 1, 0, 0, 3, 0, 3, 2, 2, 0, 0, 1, 1, 1, 2, 3, 0, 2, 1, 3, 0,
       2, 1, 1, 1, 3, 2, 2, 0, 1, 3, 3, 0, 2, 0, 3, 2, 2, 3, 3, 1, 2, 3,
       1, 2, 1, 0, 1, 3, 3, 0, 3, 3, 2, 1, 2, 0, 0, 3, 2, 3, 1, 1, 1, 0,
       3, 2, 3, 0, 1, 2, 0, 1, 3, 3, 3, 3, 2, 2, 0, 2, 1, 3, 3, 2, 1, 3,
       2, 1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 1, 1, 2, 1, 2, 2, 1, 0, 3, 0, 0,
       1, 3, 3, 3, 0, 2, 3, 0, 2, 2, 1, 3, 2, 2, 2, 2, 0, 0, 0, 2, 2, 0,
       2, 0, 2, 0, 1, 1, 3, 0, 0, 3, 0, 0, 2, 1, 1, 3, 3, 1, 3, 3, 3, 3,
       0, 3, 0, 2, 1, 3, 2, 2, 3, 3, 0, 3, 0, 3, 0, 2, 1, 1, 1, 1, 2, 3,
       1, 1, 3, 3, 2, 2, 1, 1, 3, 2, 1, 1, 1, 2, 2, 3, 1, 1, 1, 2, 2, 0,
       2, 1, 1, 3, 0, 0, 1, 2, 1, 2, 3, 1, 2, 3, 3, 1, 2, 2, 3, 0, 1, 1,
       2, 0, 2, 1, 3, 1, 2, 1, 1, 1, 3, 1, 3, 1, 3, 1, 1, 2, 1, 2, 1, 3,
       1, 0, 2, 1, 1, 2, 2, 3, 1, 3, 2, 2, 2, 0, 0, 2, 0, 1, 2, 2, 2, 0,
       1, 1, 0, 2, 0, 3, 2, 2, 1, 2, 3, 2, 2, 0, 2, 2, 0, 2, 3, 2, 3, 3,
       0, 3, 2, 1, 3, 2, 0, 0, 2, 1, 3, 2, 2, 1, 0, 2, 1, 0, 2, 0, 0, 3,
       0, 1, 3, 1, 1, 2, 0, 2, 2, 2, 3, 3, 0, 3, 0, 1, 0, 1, 2, 3, 2, 0,
       2, 1, 3, 0, 0, 3, 2, 3, 1, 1, 2, 3, 1, 3, 1, 2, 3, 3, 2, 2, 2, 0,
       3, 2, 1, 2, 2, 1, 3, 1, 0, 2, 3, 3, 3, 0, 3, 2, 1, 2, 3, 3, 0, 3,
       3, 3, 1, 2, 3, 2, 2, 1, 1, 1, 2, 3, 2, 1, 0, 3, 3, 3, 0, 2, 3, 0,
       1, 2, 1, 2, 0, 1, 2, 2, 3, 1, 3, 3, 2, 1, 2, 1, 1, 1, 0, 1, 0, 3,
       3, 3, 3, 2, 1, 1, 3, 1, 1, 2, 0, 2, 3, 2, 1, 2, 3, 1, 2, 3, 1, 2,
       2, 3, 0, 1, 2, 0, 1, 0, 3, 3, 2, 3, 2, 3, 1, 2, 2, 2, 3, 2, 2, 0,
       1, 3, 2, 1, 1, 2, 2, 3, 1, 1, 1, 0, 1, 3, 2, 2, 3, 0, 2, 1, 3, 3,
       1, 0, 3, 3, 2, 1, 2, 3, 3, 1, 1, 1, 0, 3, 1, 2, 1, 2, 2, 0, 3, 3,
       1, 2, 3, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 2, 1, 2, 2, 2, 3, 2, 2, 2,
       0, 0, 1, 2, 3, 2, 1, 1, 3, 2, 0, 3, 2, 3, 0, 2, 1, 0, 0, 0, 3, 3,
       0, 3, 3, 0, 1, 1, 3, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 3, 1, 2, 3, 0,
       2, 1, 3, 3, 1, 3, 2, 2, 0, 3, 1, 0, 2, 0, 1, 2, 3, 0, 0, 3, 2, 1,
       3, 1, 1, 2, 1, 2, 0, 1, 3, 0, 2, 1, 1, 3, 3, 0, 0, 1, 0, 2, 1, 2,
       2, 2, 2, 2, 2, 0, 3, 2, 3, 3, 3, 1, 2, 3, 2, 0, 0, 3, 2, 3, 2, 0,
       3, 2, 1, 1, 3, 3, 3, 0, 3, 2, 0, 1, 3, 3, 1, 1, 1, 2, 3, 0, 2, 3,
       3, 2, 3, 1, 3, 0, 0, 3, 3, 2])

In [144]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [145]:
from sklearn.naive_bayes import MultinomialNB

mult = MultinomialNB()

model = mult.fit(X_train,Y_train)

Y_pred = model.predict(X_test)

Y_pred

array([1, 3, 1, 3, 2, 2, 3, 1, 3, 2, 1, 1, 1, 3, 3, 2, 1, 1, 2, 1, 3, 3,
       1, 3, 2, 1, 1, 3, 3, 1, 2, 2, 2, 2, 3, 1, 1, 1, 1, 3, 3, 1, 1, 3,
       1, 3, 3, 2, 0, 1, 1, 3, 1, 2, 3, 1, 3, 3, 1, 1, 1, 1, 3, 3, 3, 1,
       1, 3, 3, 1, 3, 1, 1, 1, 2, 3, 3, 1, 1, 2, 1, 3, 2, 3, 1, 1, 3, 1,
       3, 2, 3, 3, 1, 3, 1, 1, 3, 3, 3, 3, 2, 3, 1, 1, 1, 3, 2, 2, 3, 1,
       3, 3, 2, 3, 3, 1, 1, 3, 1, 3, 2, 2, 1, 2, 2, 2, 1, 3, 2, 3, 1, 3,
       3, 3, 1, 2, 1, 3, 2, 3, 3, 3, 3, 1, 1, 2, 3, 3, 2, 3, 1, 3, 2, 1,
       1, 1, 3, 3, 1, 3, 3, 3, 3, 2, 1, 1, 2, 1, 3, 1, 3, 1, 3, 3, 0, 2,
       2, 3, 2, 1, 0, 2, 3, 3, 3, 2, 1, 3, 1, 3, 1, 1, 2, 3, 2, 2, 2, 2,
       3, 1])

In [146]:
from sklearn.metrics import accuracy_score,confusion_matrix

print(accuracy_score(Y_test,Y_pred))

print(confusion_matrix(Y_test,Y_pred))

0.51
[[ 3  7  3 18]
 [ 0 35  5 13]
 [ 0 19 28 14]
 [ 0 12  7 36]]

In [147]:
df.isna().sum()

ID                   0
Entity               0
Nature of comment    0
Comment              0
Tokens               0
Text                 0
dtype: int64

In [155]:
def custom(text):

    text = text.lower()

    text = replace_url(text)

    text = " ".join([stemmer.stem(i) for i in word_tokenize(text) if i not in stop_words])

    print(text)

    result = tfid.transform([text])

    print(result)

    new_result = model.predict(result)

    return le.inverse_transform(new_result)

print(custom(text="This is inspiring"))

inspir
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1 stored elements and shape (1, 4229)>
  Coords	Values
  (0, 1728)	1.0
['Neutral']