In [1]:
import numpy
import pandas

In [2]:
data = pandas.read_csv("cancer-risk-factors.csv")
df = pandas.DataFrame(data)
df

,Patient_ID,Cancer_Type,Age,Gender,Smoking,Alcohol_Use,Obesity,Family_History,Diet_Red_Meat,Diet_Salted_Processed,...,Physical_Activity,Air_Pollution,Occupational_Hazards,BRCA_Mutation,H_Pylori_Infection,Calcium_Intake,Overall_Risk_Score,BMI,Physical_Activity_Level,Risk_Level
0,LU0000,Breast,68,0,7,2,8,0,5,3,...,4,6,3,1,0,0,0.398696,28.0,5,Medium
1,LU0001,Prostate,74,1,8,9,8,0,0,3,...,1,3,3,0,0,5,0.424299,25.4,9,Medium
2,LU0002,Skin,55,1,7,10,7,0,3,3,...,1,8,10,0,0,6,0.605082,28.6,2,Medium
3,LU0003,Colon,61,0,6,2,2,0,6,2,...,6,4,8,0,0,8,0.318449,32.1,7,Low
4,LU0004,Lung,67,1,10,7,4,0,6,3,...,9,10,9,0,0,5,0.524358,25.1,2,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,ST0395,Colon,60,1,4,6,4,0,10,6,...,4,5,3,1,0,4,0.437539,30.3,3,Medium
1996,ST0396,Prostate,84,1,5,7,8,0,10,0,...,2,1,3,0,0,2,0.451128,25.9,4,Medium
1997,ST0397,Lung,65,0,7,2,10,0,4,2,...,3,6,0,0,1,0,0.295760,22.5,3,Low
1998,ST0398,Lung,64,1,10,2,10,0,2,10,...,5,4,2,0,0,10,0.422201,25.3,3,Medium
1999,ST0399,Breast,64,0,3,4,10,0,0,5,...,0,3,9,0,0,0,0.518137,23.0,3,Medium

In [3]:
df.dtypes

Patient_ID                  object
Cancer_Type                 object
Age                          int64
Gender                       int64
Smoking                      int64
Alcohol_Use                  int64
Obesity                      int64
Family_History               int64
Diet_Red_Meat                int64
Diet_Salted_Processed        int64
Fruit_Veg_Intake             int64
Physical_Activity            int64
Air_Pollution                int64
Occupational_Hazards         int64
BRCA_Mutation                int64
H_Pylori_Infection           int64
Calcium_Intake               int64
Overall_Risk_Score         float64
BMI                        float64
Physical_Activity_Level      int64
Risk_Level                  object
dtype: object

In [4]:
df = df.drop(columns=['Patient_ID','Gender'])
df

,Cancer_Type,Age,Smoking,Alcohol_Use,Obesity,Family_History,Diet_Red_Meat,Diet_Salted_Processed,Fruit_Veg_Intake,Physical_Activity,Air_Pollution,Occupational_Hazards,BRCA_Mutation,H_Pylori_Infection,Calcium_Intake,Overall_Risk_Score,BMI,Physical_Activity_Level,Risk_Level
0,Breast,68,7,2,8,0,5,3,7,4,6,3,1,0,0,0.398696,28.0,5,Medium
1,Prostate,74,8,9,8,0,0,3,7,1,3,3,0,0,5,0.424299,25.4,9,Medium
2,Skin,55,7,10,7,0,3,3,4,1,8,10,0,0,6,0.605082,28.6,2,Medium
3,Colon,61,6,2,2,0,6,2,4,6,4,8,0,0,8,0.318449,32.1,7,Low
4,Lung,67,10,7,4,0,6,3,10,9,10,9,0,0,5,0.524358,25.1,2,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Colon,60,4,6,4,0,10,6,4,4,5,3,1,0,4,0.437539,30.3,3,Medium
1996,Prostate,84,5,7,8,0,10,0,1,2,1,3,0,0,2,0.451128,25.9,4,Medium
1997,Lung,65,7,2,10,0,4,2,2,3,6,0,0,1,0,0.295760,22.5,3,Low
1998,Lung,64,10,2,10,0,2,10,7,5,4,2,0,0,10,0.422201,25.3,3,Medium
1999,Breast,64,3,4,10,0,0,5,1,0,3,9,0,0,0,0.518137,23.0,3,Medium

In [5]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Cancer_Type'] = le.fit_transform(df['Cancer_Type'])
df['Risk_Level'] = le.fit_transform(df['Risk_Level'])

In [6]:
df

,Cancer_Type,Age,Smoking,Alcohol_Use,Obesity,Family_History,Diet_Red_Meat,Diet_Salted_Processed,Fruit_Veg_Intake,Physical_Activity,Air_Pollution,Occupational_Hazards,BRCA_Mutation,H_Pylori_Infection,Calcium_Intake,Overall_Risk_Score,BMI,Physical_Activity_Level,Risk_Level
0,0,68,7,2,8,0,5,3,7,4,6,3,1,0,0,0.398696,28.0,5,2
1,3,74,8,9,8,0,0,3,7,1,3,3,0,0,5,0.424299,25.4,9,2
2,4,55,7,10,7,0,3,3,4,1,8,10,0,0,6,0.605082,28.6,2,2
3,1,61,6,2,2,0,6,2,4,6,4,8,0,0,8,0.318449,32.1,7,1
4,2,67,10,7,4,0,6,3,10,9,10,9,0,0,5,0.524358,25.1,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1,60,4,6,4,0,10,6,4,4,5,3,1,0,4,0.437539,30.3,3,2
1996,3,84,5,7,8,0,10,0,1,2,1,3,0,0,2,0.451128,25.9,4,2
1997,2,65,7,2,10,0,4,2,2,3,6,0,0,1,0,0.295760,22.5,3,1
1998,2,64,10,2,10,0,2,10,7,5,4,2,0,0,10,0.422201,25.3,3,2
1999,0,64,3,4,10,0,0,5,1,0,3,9,0,0,0,0.518137,23.0,3,2

In [7]:
X = df.iloc[:,:-1]
X
Y = df.iloc[:,-1]
Y

0       2
1       2
2       2
3       1
4       2
       ..
1995    2
1996    2
1997    1
1998    2
1999    2
Name: Risk_Level, Length: 2000, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3)
X_train

,Cancer_Type,Age,Smoking,Alcohol_Use,Obesity,Family_History,Diet_Red_Meat,Diet_Salted_Processed,Fruit_Veg_Intake,Physical_Activity,Air_Pollution,Occupational_Hazards,BRCA_Mutation,H_Pylori_Infection,Calcium_Intake,Overall_Risk_Score,BMI,Physical_Activity_Level
664,2,57,7,7,8,1,5,4,6,4,8,5,0,1,0,0.486186,23.1,5
1794,2,53,10,6,1,0,2,3,1,9,8,1,0,0,4,0.331613,26.9,2
1940,2,48,8,9,9,0,3,7,4,6,10,10,0,1,4,0.649947,27.2,9
795,3,59,1,6,9,1,4,0,7,3,2,5,0,0,4,0.342326,30.2,9
181,2,62,10,9,8,0,7,3,9,9,8,7,0,0,3,0.688962,22.6,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,0,53,6,8,9,0,4,3,4,4,10,6,0,0,0,0.643793,19.6,8
1321,2,61,10,2,7,0,3,5,9,3,6,1,0,0,3,0.394252,28.1,8
1588,0,74,1,2,10,1,6,2,10,0,1,3,0,0,0,0.309374,22.7,2
1803,0,64,5,8,10,1,0,6,2,0,10,0,0,0,0,0.545985,19.9,10
66,2,53,10,10,4,0,0,1,7,5,10,7,0,1,3,0.590474,25.7,1

In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [10]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()

model = knn.fit(X_train,Y_train)

In [11]:
Y_pred = model.predict(X_test)

Y_pred

array([2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2,
       2, 2, 0, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2,
       2, 0, 2, 2, 1, 2, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 0, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 0, 2, 2, 2,
       1, 1, 2, 0, 2, 2, 2, 0, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2,
       2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 2,
       2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 0, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2,
       2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2,
       2, 2, 2, 1, 2, 1])

In [12]:
from sklearn.metrics import accuracy_score

print(accuracy_score(Y_test,Y_pred))

0.87

In [13]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test,Y_pred)
cm

array([[  8,   0,  21],
       [  0,  58,  39],
       [  2,  16, 456]])