In [1]:
import numpy
import pandas

In [2]:
# Dataframe creation
data = pandas.read_csv('heart (1).csv')
df = pandas.DataFrame(data)
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [3]:
# Target  >>>  HeartDisease

In [4]:
# Unnecessory column removal
df = df.drop(columns= ['Age','Sex'],axis=1)
df

,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,ATA,130,283,0,ST,98,N,0.0,Up,0
3,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...
913,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [5]:
# Checking missing values
df.isna().sum()

ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [6]:
# Encoding

# Class = Label Encoder

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['ChestPainType'] = le.fit_transform(df['ChestPainType'])
df['RestingECG'] = le.fit_transform(df['RestingECG'])
df['ExerciseAngina'] = le.fit_transform(df['ExerciseAngina'])
df['ST_Slope'] = le.fit_transform(df['ST_Slope'])
df

,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,1,140,289,0,1,172,0,0.0,2,0
1,2,160,180,0,1,156,0,1.0,1,1
2,1,130,283,0,2,98,0,0.0,2,0
3,0,138,214,0,1,108,1,1.5,1,1
4,2,150,195,0,1,122,0,0.0,2,0
...,...,...,...,...,...,...,...,...,...,...
913,3,110,264,0,1,132,0,1.2,1,1
914,0,144,193,1,1,141,0,3.4,1,1
915,0,130,131,0,1,115,1,1.2,1,1
916,1,130,236,0,0,174,0,0.0,1,1
917,2,138,175,0,1,173,0,0.0,2,0

In [7]:
X = df.iloc[:,:-1]
X
Y = df.iloc[:,-1]
Y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

Data preprocessing steps
=====================================
Handling Missing Values
Data Transform
Outliers
Scaling
Data Reduction

In [8]:
# Splitting
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3)

X_train

,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
547,3,142,200,1,2,100,0,1.5,0
836,0,135,254,0,0,127,0,2.8,1
212,2,130,276,0,1,128,1,1.0,2
117,0,130,338,1,2,130,1,1.5,1
27,1,120,284,0,1,118,0,0.0,2
...,...,...,...,...,...,...,...,...,...
732,0,200,288,1,0,133,1,4.0,0
817,0,125,258,0,0,141,1,2.8,1
373,0,135,0,0,1,115,1,1.0,1
191,1,170,209,0,2,116,0,0.0,2
618,0,128,263,0,1,105,1,0.2,1

In [9]:
# Scaling
from sklearn.preprocessing import StandardScaler    # Z = (x - mean) / Standard_Deviation

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)     # 70 %      fit takes mean,std of 70% data

X_test = scaler.transform(X_test)   # 30 %%!    X_test is transformed using mean,std,etc.. of the 70 % data
                                               #Hence model does not see the 30 % data
X_train
X_test

array([[ 0.20963113,  1.147259  ,  0.32004197, ..., -0.81967982,
        -0.81638491,  1.09047896],
       [-0.81772142, -1.24022974, -1.76783553, ..., -0.81967982,
        -0.81638491, -0.62963773],
       [-0.81772142,  0.38760349,  0.24804619, ..., -0.81967982,
        -0.81638491,  1.09047896],
       ...,
       [-0.81772142,  0.65890903,  0.46403352, ...,  1.21998856,
         1.09401827, -0.62963773],
       [ 1.23698368, -0.15500759,  0.09505517, ..., -0.81967982,
        -0.81638491,  1.09047896],
       [-0.81772142, -0.69761867, -0.17492899, ..., -0.81967982,
        -0.43430427,  1.09047896]], shape=(276, 9))

In [10]:
# Algorithm
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()

In [11]:
# Model Creation
model = knn.fit(X_train,Y_train)

In [12]:
# Testing
y_pred = model.predict(X_test)
y_pred

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0])

In [13]:
from sklearn.metrics import accuracy_score

print(accuracy_score(Y_test,y_pred))

0.8514492753623188

In [14]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test,y_pred)
cm

array([[ 99,  22],
       [ 19, 136]])