In [40]:
import numpy
import pandas

In [41]:
data = pandas.read_csv('kidney_dataset.csv')
df = pandas.DataFrame(data)
df

,Creatinine,BUN,GFR,Urine_Output,Diabetes,Hypertension,Age,Protein_in_Urine,Water_Intake,Medication,CKD_Status
0,0.788803,8.386869,102.161787,1632.649387,0,0,27.682074,106.700203,1.570370,NaN,0
1,3.413970,53.688796,50.071257,935.540516,1,0,33.122208,410.008362,3.425287,ACE Inhibitor,1
2,0.647645,7.466540,89.451831,1774.553846,1,1,55.832284,123.336925,1.123301,Diuretic,0
3,0.795508,12.516821,99.872180,2360.602980,0,0,32.391900,116.098870,3.086846,ACE Inhibitor,0
4,0.869010,19.855960,86.110182,1987.750901,0,1,66.689515,55.668760,2.174980,ARB,0
...,...,...,...,...,...,...,...,...,...,...,...
4995,4.048737,53.094020,24.964596,1179.120228,1,1,64.910042,2846.781763,3.403640,NaN,1
4996,0.787392,7.598859,94.228637,2029.623102,0,1,49.365980,56.600073,1.759214,ACE Inhibitor,0
4997,1.177967,10.198228,89.099101,2463.843638,0,1,47.207777,88.090385,2.238708,NaN,0
4998,1.189794,12.446732,90.539937,1851.314122,1,0,31.270049,64.837267,3.188672,NaN,0
4999,1.000078,11.804883,91.697611,2056.462819,0,0,61.782239,134.514375,3.755283,ACE Inhibitor,0

In [42]:
df.isna().sum()

Creatinine             0
BUN                    0
GFR                    0
Urine_Output           0
Diabetes               0
Hypertension           0
Age                    0
Protein_in_Urine       0
Water_Intake           0
Medication          2987
CKD_Status             0
dtype: int64

In [43]:
df = df.drop(['Medication'],axis=1)

In [44]:
df.dtypes

Creatinine          float64
BUN                 float64
GFR                 float64
Urine_Output        float64
Diabetes              int64
Hypertension          int64
Age                 float64
Protein_in_Urine    float64
Water_Intake        float64
CKD_Status            int64
dtype: object

In [45]:
df

,Creatinine,BUN,GFR,Urine_Output,Diabetes,Hypertension,Age,Protein_in_Urine,Water_Intake,CKD_Status
0,0.788803,8.386869,102.161787,1632.649387,0,0,27.682074,106.700203,1.570370,0
1,3.413970,53.688796,50.071257,935.540516,1,0,33.122208,410.008362,3.425287,1
2,0.647645,7.466540,89.451831,1774.553846,1,1,55.832284,123.336925,1.123301,0
3,0.795508,12.516821,99.872180,2360.602980,0,0,32.391900,116.098870,3.086846,0
4,0.869010,19.855960,86.110182,1987.750901,0,1,66.689515,55.668760,2.174980,0
...,...,...,...,...,...,...,...,...,...,...
4995,4.048737,53.094020,24.964596,1179.120228,1,1,64.910042,2846.781763,3.403640,1
4996,0.787392,7.598859,94.228637,2029.623102,0,1,49.365980,56.600073,1.759214,0
4997,1.177967,10.198228,89.099101,2463.843638,0,1,47.207777,88.090385,2.238708,0
4998,1.189794,12.446732,90.539937,1851.314122,1,0,31.270049,64.837267,3.188672,0
4999,1.000078,11.804883,91.697611,2056.462819,0,0,61.782239,134.514375,3.755283,0

In [46]:
df['CKD_Status'].unique()

array([0, 1])

In [47]:
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]

In [48]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3)

In [49]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [50]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()

model = dt.fit(X_train,Y_train)

Y_pred = model.predict(X_test)

In [51]:
from sklearn.metrics import accuracy_score,confusion_matrix

print(accuracy_score(Y_test,Y_pred))
print(confusion_matrix(Y_test,Y_pred))

1.0
[[1104    0]
 [   0  396]]