Datatypes in numpy
object >>> "str"
int
float
bool

In [1]:
# Importing necessary libraries
import numpy
import pandas

In [2]:
# Dataframe creation
data = pandas.read_csv("heart.csv")
df = pandas.DataFrame(data)
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125.0,212,0,NaN,168.0,0,1.0,2,2.0,3.0,0
1,53,1,0,140.0,203,1,0.0,155.0,1,3.1,0,0.0,3.0,0
2,70,1,0,145.0,174,0,1.0,125.0,1,2.6,0,0.0,3.0,0
3,61,1,0,148.0,203,0,1.0,NaN,0,0.0,2,1.0,3.0,0
4,62,0,0,138.0,294,1,1.0,106.0,0,1.9,1,3.0,2.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140.0,221,0,1.0,164.0,1,0.0,2,0.0,2.0,1
1021,60,1,0,125.0,258,0,0.0,141.0,1,2.8,1,1.0,3.0,0
1022,47,1,0,110.0,275,0,0.0,118.0,1,1.0,1,1.0,2.0,0
1023,50,0,0,110.0,254,0,0.0,159.0,0,0.0,2,0.0,2.0,1
1024,54,1,0,120.0,188,0,1.0,113.0,0,1.4,1,1.0,3.0,0

In [3]:
"""
# Display first 5 rows
df.head()

# Show the shape of dataset (rows x columns)
df.shape

# Get column names and their datatypes
df.dtypes

# Find no of missing values
df.isna().sum()

# Check basic characteristics of all numeric columns
df.describe()

# Fill missing values with their mean values
df['trestbps'] = df['trestbps'].fillna(df['trestbps'].mean())
df['restecg'] = df['restecg'].fillna(df['restecg'].mean())
df['thalach'] = df['thalach'].fillna(df['thalach'].mean())
df['ca'] = df['ca'].fillna(df['ca'].mean())
df['thal'] = df['thal'].fillna(df['thal'].mean())
df.isna().sum()

# Display the patients having sex value 1
df[df['sex'] == 1]

# Display patients having sex value = 0 and age above or equal to 50
df[(df['sex'] == 0) & (df['age'] >= 50)]

# Find patients having cp = 0 and target = 1
df[(df['cp'] == 0) & (df['target'] == 1)]

# Find total count of patients having fbs = 1
(df['fbs'] == 1).sum()

# Find average values of cholestrol for men and women
df.groupby('sex')['chol'].mean()

# Find average maximum heart rate (thalach) for patients with (target = 1) and without (target = 0) disease (target)
df.groupby('target')['thalach'].mean()

# Create a new column bp_category and value will be "Normal" if trestbps < 120 else value should be "High"
df['bp_category'] = df['trestbps'].apply(lambda a: "Normal" if a < 120 else "High")
df

# Show top 5 patients having high cholestrol value
df.nlargest(5,'chol')

# Display unique values in each column
df.nunique()

# Create a new column chol_status >>> "high" if chol > 240 else "Normal"
df['chol_status'] = df['chol'].apply(lambda a: "High" if a > 240 else "Normal")
df

# 
df.sort_values('age',ascending=True)
"""

'\n# Display first 5 rows\ndf.head()\n\n# Show the shape of dataset (rows x columns)\ndf.shape\n\n# Get column names and their datatypes\ndf.dtypes\n\n# Find no of missing values\ndf.isna().sum()\n\n# Check basic characteristics of all numeric columns\ndf.describe()\n\n# Fill missing values with their mean values\ndf[\'trestbps\'] = df[\'trestbps\'].fillna(df[\'trestbps\'].mean())\ndf[\'restecg\'] = df[\'restecg\'].fillna(df[\'restecg\'].mean())\ndf[\'thalach\'] = df[\'thalach\'].fillna(df[\'thalach\'].mean())\ndf[\'ca\'] = df[\'ca\'].fillna(df[\'ca\'].mean())\ndf[\'thal\'] = df[\'thal\'].fillna(df[\'thal\'].mean())\ndf.isna().sum()\n\n# Display the patients having sex value 1\ndf[df[\'sex\'] == 1]\n\n# Display patients having sex value = 0 and age above or equal to 50\ndf[(df[\'sex\'] == 0) & (df[\'age\'] >= 50)]\n\n# Find patients having cp = 0 and target = 1\ndf[(df[\'cp\'] == 0) & (df[\'target\'] == 1)]\n\n# Find total count of patients having fbs = 1\n(df[\'fbs\'] == 1).sum()\n\n# Find average values of cholestrol for men and women\ndf.groupby(\'sex\')[\'chol\'].mean()\n\n# Find average maximum heart rate (thalach) for patients with (target = 1) and without (target = 0) disease (target)\ndf.groupby(\'target\')[\'thalach\'].mean()\n\n# Create a new column bp_category and value will be "Normal" if trestbps < 120 else value should be "High"\ndf[\'bp_category\'] = df[\'trestbps\'].apply(lambda a: "Normal" if a < 120 else "High")\ndf\n\n# Show top 5 patients having high cholestrol value\ndf.nlargest(5,\'chol\')\n\n# Display unique values in each column\ndf.nunique()\n\n# Create a new column chol_status >>> "high" if chol > 240 else "Normal"\ndf[\'chol_status\'] = df[\'chol\'].apply(lambda a: "High" if a > 240 else "Normal")\ndf\n\n# \ndf.sort_values(\'age\',ascending=True)\n'

In [4]:
# Find no of missing values
df.isna().sum()

age         0
sex         0
cp          0
trestbps    1
chol        0
fbs         0
restecg     1
thalach     1
exang       0
oldpeak     0
slope       0
ca          2
thal        1
target      0
dtype: int64

In [5]:
# Fill missing values with their mean values
df['trestbps'] = df['trestbps'].fillna(df['trestbps'].mean())

In [6]:
df['restecg'] = df['restecg'].fillna(df['restecg'].mean())

In [7]:
df['thalach'] = df['thalach'].fillna(df['thalach'].mean())

In [8]:
df['ca'] = df['ca'].fillna(df['ca'].mean())

In [9]:
df['thal'] = df['thal'].fillna(df['thal'].mean())

In [10]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [11]:
# Drop unnecessary columns
df = df.drop(columns=['age','sex'])

In [12]:
# Divide input and output
X = df.iloc[:,:-1]
X
Y = df.iloc[:,-1]
Y

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64

In [13]:
# Split dataset into training and testing sets
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3)
X_train

,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
711,0,120.0,198,0,1.0,130.0,1,1.6,1,0.0,3.0
967,2,120.0,178,1,1.0,96.0,0,0.0,2,0.0,2.0
142,3,134.0,234,0,1.0,145.0,0,2.6,1,2.0,2.0
310,0,120.0,260,0,1.0,140.0,1,3.6,1,1.0,3.0
576,3,152.0,298,1,1.0,178.0,0,1.2,1,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...
770,1,135.0,203,0,1.0,132.0,0,0.0,1,0.0,1.0
537,1,120.0,325,0,1.0,172.0,0,0.2,2,0.0,2.0
615,2,120.0,219,0,1.0,158.0,0,1.6,1,0.0,2.0
330,2,120.0,215,0,1.0,170.0,0,0.0,2,0.0,2.0
707,1,140.0,294,0,0.0,153.0,0,1.3,1,0.0,2.0

In [14]:
# Scaling the data
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)