In [1]:
import numpy
import pandas

In [2]:
data = pandas.read_csv("loan_approval.csv")
df = pandas.DataFrame(data)
df

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,False
...,...,...,...,...,...,...,...,...
1995,James Schaefer,Robertton,92163,770,12251,13,85.0,True
1996,Diana Lin,New Frank,38799,635,48259,17,40.0,False
1997,Brandon Meyer,East Haley,41957,763,16752,5,60.0,True
1998,Jason Price,Adamland,139022,360,24031,35,55.0,False
1999,Nicole Brown,New Nathantown,41188,482,31397,6,20.0,False

In [3]:
df.isna().sum()

name              0
city              0
income            0
credit_score      0
loan_amount       0
years_employed    0
points            0
loan_approved     0
dtype: int64

In [4]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['loan_approved'] = le.fit_transform(df['loan_approved'])
df

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,0
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,0
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,0
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,0
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,0
...,...,...,...,...,...,...,...,...
1995,James Schaefer,Robertton,92163,770,12251,13,85.0,1
1996,Diana Lin,New Frank,38799,635,48259,17,40.0,0
1997,Brandon Meyer,East Haley,41957,763,16752,5,60.0,1
1998,Jason Price,Adamland,139022,360,24031,35,55.0,0
1999,Nicole Brown,New Nathantown,41188,482,31397,6,20.0,0

In [5]:
X = df.iloc[:,2:-1]
X
Y = df.iloc[:,-1]
Y

0       0
1       0
2       0
3       0
4       0
       ..
1995    1
1996    0
1997    1
1998    0
1999    0
Name: loan_approved, Length: 2000, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3)

X_train

      income  credit_score  loan_amount  years_employed  points
1508   49936           496        34647              17    25.0
257   116474           333        12754              20    55.0
1293   70319           451        48772              17    35.0
975    58569           766        10661              38    80.0
1191   74657           461        19878               4    30.0
...      ...           ...          ...             ...     ...
15    107397           380         6613              31    60.0
1785   83516           717        41777               1    50.0
161    77447           401        47838              21    40.0
1619  148123           510        45126              31    50.0
1586   86450           340        20024              38    50.0

[1400 rows x 5 columns]

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_train

X_test = scaler.transform(X_test)

X_test

array([[ 0.08842008,  0.9373141 , -0.49844732,  1.1366849 ,  0.96550939],
       [-0.95177549,  1.48412726, -0.92677135, -0.95786977,  1.23493597],
       [-0.84844766, -0.0320365 ,  1.56796765,  0.88533834, -1.18990324],
       ...,
       [-1.61405351,  0.45885258,  0.28511006,  1.47181364, -0.92047666],
       [-0.69260567, -0.73419431,  0.2685466 ,  1.38803146, -1.18990324],
       [ 1.06019159,  1.22936203, -1.29236567, -1.12543415,  1.77378912]],
      shape=(600, 5))

In [8]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()

model = knn.fit(X_train,Y_train)

In [9]:
y_pred = model.predict(X_test)

In [10]:
from sklearn.metrics import accuracy_score

print(accuracy_score(Y_test,y_pred))

0.995

In [11]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test,y_pred)
cm

array([[339,   1],
       [  2, 258]])